name: 'automatic-semantic-versioned-release-test'
description: 'Auto generate realeses based on committags'
inputs:
  GITHUB_TOKEN: # id of input
    description: 'Github repository token'
    required: true
    default: ''
outputs:
  new-release-created: # id of output
    description: 'Bool if new release was created or not'
  new-version:
    description: 'String with new semantic version'
runs:
  using: 'node16'
  main: 'index.js'
